# Toxic Comment Classification

In [1]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

Load and Explore the Data

In [ ]:
df = pd.read_csv('./data/train.csv')
df.head(10)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
5,00025465d4725e87,"""\n\nCongratulations from me as well, use the ...",0,0,0,0,0,0
6,0002bcb3da6cb337,COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK,1,1,1,0,1,0
7,00031b1e95af7921,Your vandalism to the Matt Shirvington article...,0,0,0,0,0,0
8,00037261f536c51d,Sorry if the word 'nonsense' was offensive to ...,0,0,0,0,0,0
9,00040093b2687caa,alignment on this subject and which are contra...,0,0,0,0,0,0

In [6]:
print(df.info() , "/n")
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             159571 non-null  object
 1   comment_text   159571 non-null  object
 2   toxic          159571 non-null  int64
 3   severe_toxic   159571 non-null  int64
 4   obscene        159571 non-null  int64
 5   threat         159571 non-null  int64
 6   insult         159571 non-null  int64
 7   identity_hate  159571 non-null  int64
dtypes: int64(6), object(2)
memory usage: 9.7+ MB
None /n

id               0
comment_text     0
toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
dtype: int64

Data Preprocessing

In [10]:
X = df['comment_text'].fillna('')
Y = df['toxic'].astype('int')

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print(X.shape, X_train.shape, X_test.shape)

(159571,) (127656,) (31915,)

Feature Extraction

In [11]:
vectorizer = TfidfVectorizer(min_df=1, stop_words='english')

X_train_features = vectorizer.fit_transform(X_train)
X_test_features = vectorizer.transform(X_test)

Train the Model (Logistic Regression)

In [12]:
model = LogisticRegression()
model.fit(X_train_features, Y_train)

LogisticRegression()

In [13]:
X_train_prediction = model.predict(X_train_features)
training_accuracy = accuracy_score(Y_train, X_train_prediction)
print(f'Accuracy on training data : {training_accuracy}')

Accuracy on training data : 0.9600488813686783

In [14]:
X_test_prediction = model.predict(X_test_features)
test_accuracy = accuracy_score(Y_test, X_test_prediction)
print(f'Accuracy on test data : {test_accuracy}\n')
print(classification_report(Y_test, X_test_prediction))

Accuracy on test data : 0.9556321478928403

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     28859
           1       0.91      0.59      0.72      3056

    accuracy                           0.96     31915
   macro avg       0.94      0.79      0.85     31915
weighted avg       0.95      0.96      0.95     31915

Test by taking input from the user and predicting

In [ ]:
sample_comment = ["You are a great person, thank you so much for your help!"]

sample_features = vectorizer.transform(sample_comment)
prediction = model.predict(sample_features)
print(prediction)

if prediction[0] == 1:
    print('The comment is Toxic.')
else:
    print('The comment is Clean (not toxic).')

[0]
The comment is Clean (not toxic).